version: '2.4'
services:
  db:
    image: postgres:13-alpine
    env_file:
      - app/.env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    links:
      - db